name: Deploy hook every day

on:
  schedule:
    - cron: '0 9 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: curl -X POST -d {} ${{ secrets.NETLIFY_DEPLOY_HOOK_URL }}
