name: test

on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: yarn install
      - name: build
        run: yarn build
      - name: test
        run: yarn test
